on: push

name: version_bump

jobs:
  version_bump:

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: windows-latest, r: 'release'}
          # - {os: macOS-latest, r: 'release'}
          # - {os: macOS-latest, r: 'devel'}
          - {os: ubuntu-18.04, r: '3.6.3'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('tidyverse')"
          Rscript -e "install.packages('reticulate')"
          sudo apt-get install -y python3
          sudo apt-get install -y python3-pip --upgrade
          sudo apt-get install -y python3-setuptools
          pip3 install synapseclient

      - name: bump_version
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: R/version_bump.R ${{ secrets.SYN_USERNAME }} ${{ secrets.SYN_PASSWORD }}
        shell: Rscript {0}
